spring:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    serialization:
      write_dates_as_timestamps: false
  aop:
    proxy-target-class: false
  profiles:
    active: local

logging:
  level:
    com:
      huangydyn: DEBUG
    org:
      springframework:
        web: info
    root: WARN
